[package]
name = "billion"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
log = "0.4.22"
simple_logger = "5.0"
tokio = { version = "1.41.0", features = ["full"] }
rayon = "1.10.0"
futures = "0.3.31"
