[package]
name = "billion"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.9.0"
fast-float = "0.2.0"
memchr = "2.7.1"
memmap = "0.7.0"
rayon = "1.8.0"
rustc-hash = "1.1.0"
smol_str = "0.2.0"
crossbeam = "0.8.4"
