[package]
name = "billion"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.9.0"
fast-float = "0.2.0"
memchr = "2.7.1"
memmap = "0.7.0"
rayon = "1.8.0"
rustc-hash = "2.0"
smol_str = "0.3.2"
crossbeam-channel = "0.5.13"
crossbeam-deque = "0.8.5"
crossbeam-queue = "0.3.11"
